name: "cache management"
description: "Manage cache and python"


inputs:
  LOCK_PATH:
    required: true
    description: "Lock"


outputs:
  cache-hit:
    description: "cache-hit"
    value: ${{ steps.cache-node-modules.outputs.cache-hit }}


runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: "Cache pip"
      id: cache-pip
      uses: actions/cache@v3
      env:
        cache-name: cache-python
      with:
        path: |
          .venv/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('${{ inputs.LOCK_PATH }}') }}