name: 'CONTINUOUS INTEGRATION'
run-name: 'CONTINUOUS INTEGRATION'

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Run tests
      #  run: |
      #    python -m pytest --cov=app --cov-report=xml

      - name: Run linting
        run: |
          python -m flake8 --max-line-length=120